language: python

python:
  - "2.7"
sudo: false

install:
  - pip install -r requirements.txt

script:
  - cd docs
  - sphinx-build -b html ./ _build/html/
  - touch docs/_build/html/.nojekyll

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN 
  keep-history: true
  on:
    branch: master
  local_dir: docs/_build/html/