language: python

install:
  - pip install -r requirements.txt

script:
  - make html
  - touch docs/_build/html/.nojekyll

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN 
  keep-history: true
  on:
    branch: master
  local_dir: docs/_build/html/